const directions={
 v1:{title:'Current',description:'The current Clarity system, reproduced from the existing component styles with fictional content. This is the baseline for judging each proposal.'},
 v2:{title:'Refined current',description:'Keep the familiar structure and a restrained sense of depth. Reduce repeated borders, bevels, and competing controls so the content carries the screen.'},
 v3:{title:'Flat minimal',description:'Use typography, spacing, neutral surfaces, and precise separators for hierarchy. Put actions in a predictable place and keep media clear of decorative chrome.'},
 v4:{title:'Editorial workspace',description:'Organize work around projects and documents. Warm neutrals and a content-first hierarchy bring the library and customer-facing page closer together.'},
 v5:{title:'Contextual studio',description:'Build around a selected item and a focused canvas. Stable navigation and contextual tools carry one interaction model from browsing through editing and sharing.'}
};
const params=new URLSearchParams(location.search);
const state={direction:directions[params.get('direction')]?params.get('direction'):'v2',view:['library','editor','system'].includes(params.get('view'))?params.get('view'):'library',theme:params.get('theme')==='dark'?'dark':'light',compare:params.get('compare')==='1',phone:params.get('phone')==='1'};
const el=id=>document.getElementById(id);
const url=v=>`${v}/index.html?view=${state.view}&theme=${state.theme}`;
function syncFrame(frame,v){const target=new URL(url(v),location.href);if(!frame.src||new URL(frame.src).pathname!==target.pathname)frame.src=target.href;else frame.contentWindow.postMessage({type:'clarity-preview',view:state.view,theme:state.theme},location.origin)}
function render(){if(state.direction==='v1')state.compare=false;document.documentElement.dataset.reviewTheme=state.theme;el('compare').disabled=state.direction==='v1';for(const k of ['direction','view','theme'])el(k).value=state[k];const d=directions[state.direction];el('phone').setAttribute('aria-pressed',String(state.phone));el('frames').classList.toggle('phone',state.phone);el('compare').setAttribute('aria-pressed',String(state.compare));el('before').hidden=!state.compare;el('frames').classList.toggle('comparing',state.compare);el('frame-version').textContent=`${state.direction.toUpperCase()} · ${d.title}`;el('notes-version').textContent=state.direction==='v1'?'Baseline':'Design proposal';el('notes-title').textContent=d.title;el('notes-description').textContent=d.description;el('spec-link').href=`${state.direction}/DESIGN.md`;el('direct').href=url(state.direction);syncFrame(el('candidate'),state.direction);if(state.compare)syncFrame(el('baseline'),'v1');const q=new URLSearchParams({direction:state.direction,view:state.view,theme:state.theme});if(state.compare)q.set('compare','1');if(state.phone)q.set('phone','1');history.replaceState(null,'',`?${q}`)}
for(const id of ['candidate','baseline'])el(id).addEventListener('load',()=>{el(id).contentWindow.postMessage({type:'clarity-preview',view:state.view,theme:state.theme},location.origin)});
for(const k of ['direction','view','theme'])el(k).addEventListener('change',e=>{state[k]=e.target.value;render()});el('phone').addEventListener('click',()=>{state.phone=!state.phone;render()});el('compare').addEventListener('click',()=>{state.compare=!state.compare;render()});el('notes').addEventListener('click',()=>{const expanded=el('notes').getAttribute('aria-expanded')!=='true';el('notes').setAttribute('aria-expanded',String(expanded));el('notes-panel').hidden=!expanded});render();
