const assert=require('assert/strict'),base='https://pr-1042.clarity-video.workers.dev',ownMedia=[];
const get=async()=>{const r=await context.request.get(base+'/api/journey-pages/'+id);assert.equal(r.status(),200);return r.json();};
const block=(j,k)=>j.data.blocks.find(b=>b.kind===k),field=(j,k)=>block(j,k).fields;
const reset=async fn=>{const j=await get();fn(j.data);const r=await context.request.put(base+'/api/journey-pages/'+id,{data:{journey_page:j.data,base_revision:j.revision}});assert.equal(r.status(),200);await page.reload();await page.locator('[data-save-state=saved]').waitFor({state:'attached'});};
const activate=async(l,input)=>input==='pointer'?l.click():l.press('Enter');
const evidence=async(name,data)=>{fs.writeFileSync(out+'/'+name+'-ui.json',JSON.stringify(data,null,2));await shot('representative-'+name);};
try {
await sec('hero').getByRole('button',{name:'Overview media Add media',exact:true}).click();
const uploadResponse=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/tree/nodes'&&r.request().method()==='POST'&&r.ok());
await page.locator('input[type=file]').setInputFiles('/tmp/verify-land/round2/R2-checklist-final.png');
const uploaded=(await(await uploadResponse).json()).data.node;ownMedia.push(uploaded);fs.writeFileSync(out+'/owned-media.json',JSON.stringify(ownMedia,null,2));assert.equal(uploaded.name,'R2-checklist-final');
await page.waitForTimeout(3000);await page.keyboard.press('Escape');const seeded=await saved('checklist-hero-seed',j=>!!field(j,'hero').media.assetId);const image=field(seeded,'hero').media;
await reset(d=>{const li=d.blocks.findIndex(b=>b.kind==='logos'),logos=d.blocks.splice(li,1)[0];d.blocks.splice(d.blocks.findIndex(b=>b.kind==='gallery')+1,0,logos);for(const k of ['logos','gallery'])Object.assign(d.blocks.find(b=>b.kind===k).fields,{images:[{image_id:image.assetId}],title:'Checklist '+k});});
for(const input of ['pointer'])for(const [label,count,target] of [['seventh',7,7],['duplicate',3,2]])await test(input+'-logos-remove-'+label,async()=>{await reset(d=>{Object.assign(d.blocks.find(b=>b.kind==='logos').fields,{variant:'static',images:Array.from({length:count},()=>({image_id:image.assetId}))});});await sec('logos').locator('[data-logo-occurrence]').nth(count-1).waitFor({state:'attached'});assert.equal(await sec('logos').locator('[data-logo-occurrence]').count(),count);await page.waitForFunction(()=>[...document.querySelectorAll('[data-section-kind=logos] img')].every(i=>i.complete&&i.naturalWidth>0));await page.waitForTimeout(350);const remove=sec('logos').getByRole('button',{name:'Remove logo '+target,exact:true});if(input==='pointer')await remove.locator('..').hover();await activate(remove,input);await saved(input+'-logos-remove-'+label,j=>field(j,'logos').images.length===count-1&&field(j,'logos').images.every(x=>x.image_id===image.assetId));await sec('logos').locator('[data-logo-occurrence]').nth(count-2).waitFor({state:'attached'});assert.equal(await sec('logos').locator('[data-logo-occurrence]').count(),count-1);await evidence(input+'-logos-remove-'+label,{before:count,after:count-1,target});});

for(const input of ['pointer','keyboard'])await test(input+'-gallery-title-clear-default',async()=>{await reset(d=>{d.blocks.find(b=>b.kind==='gallery').fields.title='Clear me';});const t=sec('gallery').locator('h2[contenteditable]');await t.waitFor();if(input==='pointer')await t.click();else await t.focus();await t.fill('');await t.press('Tab');await saved(input+'-gallery-title-clear-default',j=>field(j,'gallery').title==='Gallery');assert.equal(await t.innerText(),'Gallery');});
for(const input of ['keyboard'])for(const [label,kind] of [['Client logos','logos'],['Gallery','gallery'],['Document','document']])await test(input+'-section-add-remove-'+kind,async()=>{const before=await get(),ids=before.data.blocks.map(b=>b.id);await activate(page.locator('[data-section-handle]').last(),input);const submenu=page.getByRole('menuitem',{name:'Add section below',exact:true});if(input==='pointer')await submenu.hover();else await submenu.press('ArrowRight');await activate(page.getByRole('menu',{name:'Add section below',exact:true}).getByRole('menuitem',{name:label,exact:true}),input);const after=await saved(input+'-section-add-'+kind,j=>j.data.blocks.length===ids.length+1&&j.data.blocks.some(b=>b.kind===kind&&!ids.includes(b.id)));const fresh=after.data.blocks.find(b=>!ids.includes(b.id));assert.equal(await page.locator('[data-slot=journey-preview] [data-section-id="'+fresh.id+'"]').count(),1);const handle=page.locator('[data-section-handle="'+fresh.id+'"]');if(await handle.count()){await activate(handle,input);await activate(page.getByRole('menuitem',{name:'Remove section',exact:true}),input);}else{await activate(page.locator('[data-section-id="'+fresh.id+'"]').getByRole('button',{name:'Logo settings',exact:true}),input);await activate(page.getByRole('button',{name:'Remove client logos section',exact:true}),input);}await saved(input+'-section-remove-'+kind,j=>!j.data.blocks.some(b=>b.id===fresh.id));assert.equal(await page.locator('[data-slot=journey-preview] [data-section-id="'+fresh.id+'"]').count(),0);});
}finally{const checks=[];for(const n of ownMedia){const r=await context.request.delete(base+'/api/tree/nodes/'+encodeURIComponent(n.id));const after=await context.request.get(base+'/api/tree/nodes/'+encodeURIComponent(n.id)+'/path');checks.push({id:n.id,name:n.name,deleteStatus:r.status(),getStatus:after.status()});}fs.writeFileSync(out+'/media-cleanup.json',JSON.stringify(checks,null,2));assert.ok(checks.every(c=>c.deleteStatus===200&&c.getStatus===404));}
