const assert=require('assert/strict'),base='https://pr-1042.clarity-video.workers.dev',ownMedia=[];
const get=async()=>{const r=await context.request.get(base+'/api/journey-pages/'+id);assert.equal(r.status(),200);return r.json();};
const block=(j,k)=>j.data.blocks.find(b=>b.kind===k),field=(j,k)=>block(j,k).fields;
const reset=async fn=>{const j=await get();fn(j.data);const r=await context.request.put(base+'/api/journey-pages/'+id,{data:{journey_page:j.data,base_revision:j.revision}});assert.equal(r.status(),200);await page.reload();await page.locator('[data-save-state=saved]').waitFor({state:'attached'});};
const activate=async(l,input)=>input==='pointer'?l.click():l.press('Enter');
const evidence=async(name,data)=>{fs.writeFileSync(out+'/'+name+'-ui.json',JSON.stringify(data,null,2));await shot('representative-'+name);};
try {
await sec('hero').getByRole('button',{name:'Overview media Add media',exact:true}).click();
const uploadResponse=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/tree/nodes'&&r.request().method()==='POST'&&r.ok());
await page.locator('input[type=file]').setInputFiles('/tmp/verify-land/round2/R2-checklist-recheck.png');
const uploaded=(await(await uploadResponse).json()).data.node;ownMedia.push(uploaded);fs.writeFileSync(out+'/owned-media.json',JSON.stringify(ownMedia,null,2));assert.equal(uploaded.name,'R2-checklist-recheck');
await page.waitForTimeout(3000);await page.keyboard.press('Escape');const seeded=await saved('checklist-hero-seed',j=>!!field(j,'hero').media.assetId);const image=field(seeded,'hero').media;
await reset(d=>{const li=d.blocks.findIndex(b=>b.kind==='logos'),logos=d.blocks.splice(li,1)[0];d.blocks.splice(d.blocks.findIndex(b=>b.kind==='gallery')+1,0,logos);for(const k of ['logos','gallery'])Object.assign(d.blocks.find(b=>b.kind===k).fields,{images:[{image_id:image.assetId}],title:'Checklist '+k});});
for(const input of ['pointer','keyboard'])for(const [label,count,target] of [['seventh',7,7],['duplicate',3,2]])await test(input+'-logos-remove-'+label,async()=>{await reset(d=>{Object.assign(d.blocks.find(b=>b.kind==='logos').fields,{variant:'static',images:Array.from({length:count},()=>({image_id:image.assetId}))});});await sec('logos').locator('[data-logo-occurrence]').nth(count-1).waitFor({state:'attached'});assert.equal(await sec('logos').locator('[data-logo-occurrence]').count(),count);const remove=sec('logos').getByRole('button',{name:'Remove logo '+target,exact:true});if(input==='pointer')await remove.locator('..').hover();await activate(remove,input);await saved(input+'-logos-remove-'+label,j=>field(j,'logos').images.length===count-1&&field(j,'logos').images.every(x=>x.image_id===image.assetId));await sec('logos').locator('[data-logo-occurrence]').nth(count-2).waitFor({state:'attached'});assert.equal(await sec('logos').locator('[data-logo-occurrence]').count(),count-1);await evidence(input+'-logos-remove-'+label,{before:count,after:count-1,target});});
async function tabTo(name){await page.mouse.move(0,0);await sec('hero').locator('h1').focus();const stops=[];for(let i=0;i<45;i++){await page.keyboard.press('Tab');await page.waitForTimeout(150);const a=await page.evaluate(()=>{const e=document.activeElement;return {tag:e.tagName,label:e.getAttribute('aria-label'),title:e.getAttribute('title'),text:e.textContent,group:e.closest('[role=group]')?.getAttribute('aria-label')};});stops.push(a);if(a.group==='Hero media controls'&&(a.label===name||a.title===name||a.text===name)){await evidence('hero-tab-'+name,stops);return;}}throw Error('Tab did not reach hero '+name+' '+JSON.stringify(stops));}
await test('hero-real-Tab-edit-remove',async()=>{await sec('hero').locator('[data-slot=media-overlay] img').waitFor();await page.waitForFunction(()=>{const i=document.querySelector('[data-section-kind=hero] [data-slot=media-overlay] img');return i?.complete&&i.naturalWidth>0});await tabTo('Edit');await page.keyboard.press('Enter');await page.getByRole('dialog').waitFor();await evidence('hero-tab-edit-dialog',{open:true});await page.keyboard.press('Escape');await tabTo('Remove');await page.keyboard.press('Enter');await saved('hero-real-Tab-edit-remove',j=>!field(j,'hero').media.assetId);assert.equal(await sec('hero').getByRole('button',{name:'Overview media Add media',exact:true}).count(),1);});
}finally{const checks=[];for(const n of ownMedia){const r=await context.request.delete(base+'/api/tree/nodes/'+encodeURIComponent(n.id));const after=await context.request.get(base+'/api/tree/nodes/'+encodeURIComponent(n.id)+'/path');checks.push({id:n.id,name:n.name,deleteStatus:r.status(),getStatus:after.status()});}fs.writeFileSync(out+'/media-cleanup.json',JSON.stringify(checks,null,2));assert.ok(checks.every(c=>c.deleteStatus===200&&c.getStatus===404));}
