import React, {useLayoutEffect, useReducer, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {renderToStaticMarkup} from 'react-dom/server';
import {Accordion} from '@base-ui/react/accordion';
import {Video, RectangleEllipsis, ChevronDown, Play, X} from 'lucide-react';
let variant='accordion', accordionOpen=true;
const cases=window.SCENARIOS;
let caseId=new URLSearchParams(location.search).get('case')||cases[0].id;
let d=cases.find(x=>x.id===caseId)||cases[0],elementView=d.videos.length?'video':'cta',videoId=d.videos[0]?.id,buttonId=d.buttons[0]?.id,onlyActivity=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0');
const when=s=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Stockholm'}).format(new Date(s));
const watchSeconds=p=>p?(p.ranges||[]).reduce((n,[a,b])=>n+Math.max(0,Math.min(b,p.duration)-Math.max(0,a)),0):0;
const percent=p=>p?.duration?Math.round(watchSeconds(p)/p.duration*100):0;
const hasPlay=s=>Object.values(s.videos).some(p=>watchSeconds(p)>0);
const countVideo=id=>d.sessions.filter(s=>watchSeconds(s.videos[id])>0).length;
const countButton=id=>d.sessions.filter(s=>s.clicks.includes(id)).length;
function miniVideo(v){const n=countVideo(v.id);return `<button id="mini-${esc(v.id)}" class="preview-video ${(variant!=='accordion'||accordionOpen)&&elementView==='video'&&videoId===v.id?'active-target':''}" onclick="pickElement('video','${esc(v.id)}')" aria-label="Inspect ${esc(v.title)}">${v.poster?`<img src="${esc(v.poster)}" alt="">`:''}<span class="play-dot">▶</span>${n?`<span class="pin">${n}</span>`:''}</button>`}
function miniButton(b){const n=countButton(b.id);return `<button id="mini-${esc(b.id)}" class="preview-cta ${(variant!=='accordion'||accordionOpen)&&elementView==='cta'&&buttonId===b.id?'active-target':''}" onclick="pickElement('cta','${esc(b.id)}')" aria-label="Inspect ${esc(b.label)}">${esc(b.label)}${n?`<span class="pin">${n}</span>`:''}</button>`}
function mini(){return `<div class="mini-wrap"><div class="mini"><div class="browserbar"><i></i><i></i><i></i><span>clarity.video</span></div><div class="paper"><div class="brandline"></div><h2>${esc(d.hero)}</h2>${d.videos[0]?miniVideo(d.videos[0]):'<p class="plain-page">A proposal with the approach, the deliverables, and a clear next step for your team.</p>'}<div class="copy-lines"><i></i><i></i><i></i></div>${d.buttons[0]?miniButton(d.buttons[0]):''}<div class="logos"><i></i><i></i><i></i><i></i></div>${d.videos.slice(1).map(v=>`<div class="secondary-media"><h3>${esc(v.title)}</h3>${miniVideo(v)}</div>`).join('')}${d.buttons.slice(1).map(miniButton).join('')}${d.blocks.filter(b=>b.kind==='story').slice(0,d.videos.length>1?1:2).map(b=>`<div class="mini-section"><h3>${esc(b.title)}</h3><div class="copy-lines"><i></i><i></i><i></i></div></div>`).join('')}</div></div><p class="preview-caption">${d.videos.length?'Select the video or button':'Select the page button'}</p></div>`}
function metrics(){return `<div class="measures"><div class="measure"><strong>${d.sessions.length}</strong><span>Page visits</span></div>${d.videos.length?`<div class="measure"><strong>${d.sessions.filter(hasPlay).length}</strong><span>Watched video</span></div>`:''}<div class="measure"><strong>${d.sessions.filter(s=>s.clicks.length).length}</strong><span>Clicked button</span></div></div>`}
function graph(v){const plays=d.sessions.filter(s=>watchSeconds(s.videos[v.id])>0);if(!plays.length)return '<div class="empty-chart">No video plays yet</div>';const N=80;const counts=Array.from({length:N+1},(_,i)=>plays.filter(s=>s.videos[v.id].ranges.some(([a,b])=>a<=v.duration*i/N&&b>v.duration*i/N)).length);const max=Math.max(...counts,1);let line=`M0,${100-counts[0]/max*94}`;for(let i=1;i<=N;i++)line+=` H${i/N*1000} V${100-counts[i]/max*94}`;const area=line+' L1000,100 L0,100 Z';return `<div class="graph"><div class="graph-area"><svg class="graph-svg" viewBox="0 0 1000 100" preserveAspectRatio="none" role="img" aria-label="Recorded visits watching each moment of ${esc(v.title)}"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#8babee" stop-opacity=".45"/><stop offset="100%" stop-color="#e4edfc" stop-opacity=".1"/></linearGradient></defs><path d="${area}" fill="url(#fill)"/><path d="${line}" fill="none" stroke="#5680e5" stroke-width="2" vector-effect="non-scaling-stroke"/>${counts.slice(0,-1).map((n,i)=>`<rect x="${i/N*1000}" y="0" width="${1000/N}" height="100" fill="transparent"><title>${fmt(v.duration*i/N)} · ${n} ${n===1?'visit':'visits'}</title></rect>`).join('')}</svg></div><div class="graph-axis"></div><div class="ticks">${[0,.25,.5,.75,1].map(x=>`<span>${fmt(v.duration*x)}</span>`).join('')}</div></div>`}
function active(s){return elementView==='video'?watchSeconds(s.videos[videoId])>0:s.clicks.includes(buttonId)}
function visitList(){const count=d.sessions.filter(active).length;const shown=onlyActivity?d.sessions.filter(active):d.sessions;return `<div class="list-heading"><span>${onlyActivity?'Matching visits':'Visits'} · ${shown.length}</span>${count&&d.sessions.length>1?`<button class="${onlyActivity?'on':''}" aria-pressed="${onlyActivity}" onclick="onlyActivity=!onlyActivity;render()">${onlyActivity?'Show all visits':elementView==='video'?'Only watched':'Only clicked'}</button>`:''}</div><div class="focus-list">${shown.length?shown.map(s=>{const p=s.videos[videoId],number=d.sessions.indexOf(s)+1;const value=elementView==='video'?watchSeconds(p)>0?`<span class="result progress">${percent(p)}% watched</span>`:p?.loaded?'<span class="result none">No progress</span>':'<span class="result none">No play recorded</span>':s.clicks.includes(buttonId)?'<span class="result yes"><i>✓</i> Clicked</span>':'<span class="result none">No click</span>';return `<div class="focus-row"><div class="place"><div class="visit-label" title="${esc(s.location||'Location unavailable')}">${esc(s.location||'Visit '+number)}</div><span class="when">${when(s.date)}</span></div>${value}</div>`}).join(''):`<div class="empty-list"><b>${d.sessions.length?'No matching visits':'No visits yet'}</b>${d.sessions.length?'Try showing all visits.':'Activity will appear after this page is opened.'}</div>`}</div>`}
function detail(){if(elementView==='video'){const v=d.videos.find(x=>x.id===videoId);if(!v)return '<div class="no-elements">This page has no video.</div>';const played=d.sessions.filter(s=>watchSeconds(s.videos[v.id])>0),avg=played.length?Math.round(played.reduce((n,s)=>n+percent(s.videos[v.id]),0)/played.length):0;return `${d.videos.length>1?`<select class="element-picker" aria-label="Choose video" onchange="pickElement('video',this.value)">${d.videos.map(x=>`<option value="${esc(x.id)}" ${x.id===v.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select>`:''}<div class="focus-head"><div><h2>${esc(v.title)}</h2><p>${fmt(v.duration)} · ${played.length} recorded ${played.length===1?'play':'plays'}</p></div><span class="soft-label">On this page</span></div>${graph(v)}${played.length?`<div class="coverage"><span>${avg}% average watched</span><span>Among recorded plays</span></div>`:''}${visitList()}`};const b=d.buttons.find(x=>x.id===buttonId);if(!b)return '<div class="no-elements">This page has no button.</div>';const clicked=countButton(b.id);return `${d.buttons.length>1?`<select class="element-picker" aria-label="Choose button" onchange="pickElement('cta',this.value)">${d.buttons.map(x=>`<option value="${esc(x.id)}" ${x.id===b.id?'selected':''}>${esc(x.label)}</option>`).join('')}</select>`:''}<div class="focus-head"><div><h2>${esc(b.label)}</h2><p>Page button</p></div><span class="soft-label">Button clicks</span></div><div class="click-summary"><strong>${clicked}</strong><span>${d.sessions.length?'of '+d.sessions.length+' visits<br>clicked this button':'clicks so far'}</span></div>${d.sessions.length?`<div class="click-bars" aria-label="${clicked} of ${d.sessions.length} visits clicked"><i class="on" style="flex:${clicked||.001}"></i><i style="flex:${Math.max(d.sessions.length-clicked,.001)}"></i></div>`:''}${visitList()}`}

const playIcon=renderToStaticMarkup(<Play size={12} fill="currentColor" aria-hidden="true"/>);
let repaint;
function render(){repaint?.()}
function pickElement(type,id){elementView=type; if(type==='video')videoId=id;else buttonId=id;accordionOpen=true;onlyActivity=false;render()}
function setScenario(id){d=cases.find(x=>x.id===id)||cases[0];caseId=d.id;elementView=d.videos.length?'video':'cta';videoId=d.videos[0]?.id;buttonId=d.buttons[0]?.id;accordionOpen=true;onlyActivity=false;const url=new URL(location);url.searchParams.set('case',d.id);history.replaceState({},'',url);render()}
Object.assign(window,{pickElement,setScenario,render});
Object.defineProperty(window,'onlyActivity',{get:()=>onlyActivity,set:v=>onlyActivity=v});
function elements(){return [d.videos[0]&&{type:'video',item:d.videos[0]},d.buttons[0]&&{type:'cta',item:d.buttons[0]},...d.videos.slice(1).map(item=>({type:'video',item})),...d.buttons.slice(1).map(item=>({type:'cta',item}))].filter(Boolean)}
function panelHTML(type,item){const old=[elementView,videoId,buttonId];elementView=type;if(type==='video')videoId=item.id;else buttonId=item.id;const html=detail();[elementView,videoId,buttonId]=old;return html}
const Preview=React.memo(function Preview({scenario}){return <div className="stable-preview" dangerouslySetInnerHTML={{__html:mini().replaceAll('▶',playIcon)}}/>});
function App(){const [,update]=useReducer(x=>x+1,0);repaint=update;const region=useRef(null);const current=accordionOpen?elementView+':'+(elementView==='video'?videoId:buttonId):null;const items=elements();
useLayoutEffect(()=>{const root=region.current;function measure(){const headers=[...root.querySelectorAll('.acc-trigger')].reduce((n,x)=>n+x.getBoundingClientRect().height+1,0);root.style.setProperty('--open-size',Math.max(230,root.clientHeight-headers-2)+'px')}measure();const observer=new ResizeObserver(measure);observer.observe(root);root.querySelectorAll('.acc-trigger').forEach(x=>observer.observe(x));return()=>observer.disconnect()},[d.id]);
useLayoutEffect(()=>{document.getElementById('page-name').textContent=d.title;document.getElementById('scenario').value=d.id;document.getElementById('data-kind').textContent=d.real?'Real snapshot':'Sample data';document.querySelectorAll('.active-target').forEach(x=>x.classList.remove('active-target'));const target=accordionOpen&&document.getElementById('mini-'+(elementView==='video'?videoId:buttonId));if(target){target.classList.add('active-target');const container=document.querySelector('.mini');const a=target.getBoundingClientRect(),b=container.getBoundingClientRect(),scale=b.width/container.offsetWidth;if(a.top<b.top||a.bottom>b.bottom)container.scrollTo({top:container.scrollTop+(a.top-b.top)/scale-container.clientHeight/2+target.offsetHeight/2,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}},[current,d.id]);
return <div className="explore stable-explore"><Preview scenario={d.id}/><div className="stats-column"><div dangerouslySetInnerHTML={{__html:metrics()}}/><div className="accordion-space" ref={region}><Accordion.Root className="accordions" value={current?[current]:[]} onValueChange={values=>{if(values.length){const [type,id]=values[0].split(':');pickElement(type,id)}else{accordionOpen=false;render()}}}>{items.map(({type,item})=>{const key=type+':'+item.id,count=type==='video'?countVideo(item.id):countButton(item.id);return <Accordion.Item className="acc-item" key={key} value={key}><Accordion.Header><Accordion.Trigger className="acc-trigger"><span className="acc-icon">{type==='video'?<Video size={18}/>:<RectangleEllipsis size={18}/>}</span><span className="acc-label">{item.title||item.label}<small>{type==='video'?'Video · '+fmt(item.duration):'Button'}</small></span><span className="acc-count">{count} {type==='video'?(count===1?'play':'plays'):(count===1?'click':'clicks')}</span><ChevronDown className="acc-chevron" size={16}/></Accordion.Trigger></Accordion.Header><Accordion.Panel className="smooth-panel" keepMounted><div className="acc-panel" dangerouslySetInnerHTML={{__html:panelHTML(type,item)}}/></Accordion.Panel></Accordion.Item>})}</Accordion.Root></div></div></div>}
document.getElementById('scenario').innerHTML=cases.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}</option>`).join('');document.body.dataset.variant='accordion';document.querySelector('.close').innerHTML=renderToStaticMarkup(<X size={20}/>);document.addEventListener('keydown',e=>{if(e.key==='Escape')document.body.classList.add('closed')});createRoot(document.getElementById('content')).render(<App/>);
