const flow=process.env.FLOW,seconds=Number(process.env.SECONDS),title='Run3 '+flow;
page.on('pageerror',e=>log({flow,pageerror:e.message}));page.on('response',r=>{if(r.status()>=400)log({flow,httpError:r.status(),url:r.url().split('?')[0]})});
await page.waitForFunction(()=>[...document.querySelectorAll('video')].some(v=>v.videoWidth>0),{},{timeout:25000});
const t=Date.now();await page.getByRole('button',{name:/^Record (camera|screen|split)/}).click();log({flow,recordStart:t});
const speech=()=>spawn('say',['-a','71','-r','170',`Clarity ${flow} recording. The Mux migration is being tested with a real microphone. Twenty three clear words should appear in the captions. Small text and motion must stay readable.`]);speech();let next=60000;while(Date.now()-t<seconds*1000-400){await sleep(Math.min(1000,seconds*1000-(Date.now()-t)-300));if(Date.now()-t>=next){speech();next+=60000;log({flow,recordingElapsedMs:Date.now()-t})}}
await shot(flow+'-recording');await sleep(Math.max(0,t+seconds*1000-Date.now()));const stop=Date.now();await page.getByRole('button',{name:/^Stop ·/}).click();log({flow,actualRecordingMs:stop-t,stop});await shot(flow+'-stopped');
await page.getByRole('button',{name:'Copy link',exact:true}).waitFor({timeout:180000});log({flow,linkReadyMs:Date.now()-stop});await page.getByRole('link',{name:'Videos',exact:true}).click();
const card=page.getByRole('button',{name:'Play Untitled Video',exact:true}).first();await card.waitFor();await card.locator('img').waitFor({timeout:90000});log({flow,posterMs:Date.now()-stop});const play=Date.now();await card.click();await page.waitForFunction(()=>[...document.querySelectorAll('video')].some(v=>v.currentTime>0&&!v.paused&&v.videoWidth>0),{},{timeout:90000});log({flow,stopToPlayableMs:Date.now()-stop,firstFrameMs:Date.now()-play});await shot(flow+'-playable');
await page.getByRole('button',{name:'Actions for Untitled Video',exact:true}).first().click();await page.getByRole('menuitem',{name:'Rename',exact:true}).click();const input=page.getByRole('textbox',{name:'',exact:true});await input.fill(title);await input.press('Enter');log({flow,title});
