async function stagingLogin(req,url,opts){for(let attempt=0;attempt<6;attempt++){try{return await req.post(url,opts)}catch(e){if(attempt===5||!/EHOSTUNREACH|ECONNREFUSED|ETIMEDOUT/.test(e.message))throw e;await new Promise(r=>setTimeout(r,700));}}}
process.env.NODE_OPTIONS=[process.env.NODE_OPTIONS,'--dns-result-order=ipv4first'].filter(Boolean).join(' ');
require('node:dns').setDefaultResultOrder('ipv4first');
const fs=require('fs'),crypto=require('crypto');const root='/Users/williamlarsten/Development/clarity-overnight-1006/v-land',out='/Users/williamlarsten/Development/clarity-overnight-1006/verify/land/browser/clearing-links';fs.mkdirSync(out,{recursive:true});const {chromium}=require('./instrument.cjs');const env=Object.fromEntries(fs.readFileSync(root+'/.env.e2e.local','utf8').split('\n').filter(x=>/^[A-Z0-9_]+=/.test(x)).map(x=>{let i=x.indexOf('=');return[x.slice(0,i),x.slice(i+1).trim().replace(/^['"]|['"]$/g,'')]}));const base='https://pr-1042.clarity-video.workers.dev';
(async()=>{let mode='main',id;const browser=await chromium.launch();const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),page=await ctx.newPage();page.setDefaultTimeout(5000);const results=[],errors=[];page.on('pageerror',e=>errors.push({mode,error:e.message}));page.on('console',m=>{if(m.type()==='error')errors.push({mode,error:m.text()})});const a=await stagingLogin(ctx.request,base+'/auth/password',{data:{email:env.E2E_USER_PRO_EMAIL,password:env.E2E_USER_PRO_PASSWORD}});if(!a.ok())throw Error('auth '+a.status());
const source=JSON.parse(fs.readFileSync('/tmp/verify-land/scripts/fixture.json')).data;
const cases=[];for(const [i,key] of ['primaryCta','signCta','paymentCta','customCta'].entries())for(const field of ['link','label'])cases.push({name:key+'-'+field,kind:'hero',path:[key,field],key,index:i,field});for(const kind of ['pricing','form'])for(const field of ['link','label'])cases.push({name:kind+'-'+field,kind,field,path:kind==='pricing'?['pricings',0,field==='link'?'cta_link':'cta']:['form',field==='link'?'cta_link':'cta']});
const read=(j,c)=>c.path.reduce((o,k)=>o?.[k],j.data.blocks.find(b=>b.kind===c.kind).fields);
try{for(mode of ['branch']){const blocks=structuredClone(source.blocks);for(const b of blocks){b.id=crypto.randomUUID();if('title' in b.fields)b.fields.title='Seed '+b.kind;if(b.kind==='story')b.fields.body='<p>Seed description</p>';if(b.kind==='faq')b.fields.questions=[{question:'Seed question',answer:'Seed answer',seq_no:'1'}];if(b.kind==='pricing')b.fields.pricings=[{...b.fields.pricings[0],title:'Seed plan',price:'99',description:'<p>Seed plan body</p>',features:[{feature:'Seed feature',seq_no:'1'}],cta:'Seed CTA',cta_link:'https://example.com'}];if(b.kind==='form')Object.assign(b.fields.form,{form_title:'Seed form',form_description:'<p>Seed form body</p>',cta:'Send',cta_link:'https://example.com'});}
for(const [i,key] of ['primaryCta','signCta','paymentCta','customCta'].entries())Object.assign(blocks.find(b=>b.kind==='hero').fields[key],{enabled:true,label:'Seed '+key,link:'https://example.com/'+i});const seed=structuredClone(blocks);
const cr=await ctx.request.post(base+'/api/journey-pages',{data:{journey_page:{name:'Overnight verify LAND '+new Date().toISOString().slice(11,19),blocks}}});if(cr.status()!==201)throw Error('create '+cr.status());id=(await cr.json()).data.id;fs.appendFileSync(out+'/owned.ndjson',JSON.stringify({id,name:'Overnight verify LAND',time:new Date().toISOString()})+'\n');await page.goto(base+'/edit/'+id);await page.locator('[data-slot="save-status"]').waitFor({state:'attached'});await page.screenshot({path:out+'/'+mode+'-before.png',fullPage:true});
for(const c of cases){const result={mode,name:c.name};try{const current=await(await ctx.request.get(base+'/api/journey-pages/'+id)).json();const reset=await ctx.request.put(base+'/api/journey-pages/'+id,{data:{journey_page:{...current.data,blocks:seed},base_revision:current.revision}});if(!reset.ok())throw Error('reset '+reset.status());await page.reload();await page.locator('[data-slot="save-status"][data-save-state="saved"]').waitFor({state:'attached'});const section=page.locator(mode==='main'?'.accordion-section[data-section-kind="'+c.kind+'"]':'[data-slot="journey-preview"] [data-section-kind="'+c.kind+'"]');let loc;if(mode==='main'){if(c.kind==='hero')loc=section.locator('[data-slot="cta-group"]').nth(c.index).getByRole('textbox').nth(c.field==='label'?0:1);else loc=section.getByLabel(c.kind==='pricing'?(c.field==='link'?'CTA link':'CTA label'):(c.field==='link'?'Redirect URL':'Submit button label'),{exact:true}).first();}else{const trigger=c.kind==='hero'?section.locator('[data-slot="cta-trigger"]').filter({hasText:'Seed '+c.key}):section.locator('[data-slot="cta-trigger"]').first();await trigger.hover();await trigger.locator('[contenteditable]').first().focus();await page.locator('[data-slot="cta-editor-card"]').waitFor();loc=c.field==='link'?page.locator('[data-slot="cta-editor-card"]').getByRole('textbox',{name:'Link',exact:true}):page.locator('[data-slot="cta-editor-card"]').getByPlaceholder('Label');}
await loc.click();await loc.fill('');await loc.press('Tab');await page.waitForTimeout(1400);await page.locator('[data-slot="save-status"][data-save-state="saved"]').waitFor({timeout:30000,state:'attached'});await page.reload();await page.locator('[data-slot="save-status"][data-save-state="saved"]').waitFor({state:'attached'});const j=await(await ctx.request.get(base+'/api/journey-pages/'+id)).json();fs.writeFileSync(out+'/'+mode+'-'+c.name+'.json',JSON.stringify(j,null,2));result.stored=read(j,c);result.status=result.stored===''?'CLEARED':'RETAINED_OR_DEFAULTED';result.domCount=await section.count();await section.scrollIntoViewIfNeeded().catch(()=>{});await page.screenshot({path:out+'/'+mode+'-'+c.name+'.png'});}catch(e){result.status='UNVERIFIED';result.error=e.message;}results.push(result);fs.writeFileSync(out+'/results.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify(result));}
const d=await ctx.request.delete(base+'/api/journey-pages/'+id);results.push({mode,cleanup:id,status:d.status(),getStatus:(await ctx.request.get(base+'/api/journey-pages/'+id)).status()});id=null;}}
finally{if(id)results.push({cleanup:id,status:(await ctx.request.delete(base+'/api/journey-pages/'+id)).status(),getStatus:(await ctx.request.get(base+'/api/journey-pages/'+id)).status()});fs.writeFileSync(out+'/results.json',JSON.stringify({results,errors},null,2));await browser.close()}
})().catch(e=>{console.log(e.message);process.exitCode=1});
