async function stagingLogin(req,url,opts){for(let attempt=0;attempt<6;attempt++){try{return await req.post(url,opts)}catch(e){if(attempt===5||!/EHOSTUNREACH|ECONNREFUSED|ETIMEDOUT/.test(e.message))throw e;await new Promise(r=>setTimeout(r,700));}}}
process.env.NODE_OPTIONS=[process.env.NODE_OPTIONS,'--dns-result-order=ipv4first'].filter(Boolean).join(' ');
require('node:dns').setDefaultResultOrder('ipv4first');
const fs=require('fs');
const root='/Users/williamlarsten/Development/clarity-overnight-1006/v-land';
const out='/Users/williamlarsten/Development/clarity-overnight-1006/verify/land/browser/empty-story';
const {chromium}=require('./instrument.cjs');
fs.mkdirSync(out,{recursive:true});
const env=Object.fromEntries(fs.readFileSync(root+'/.env.e2e.local','utf8').split('\n').filter(x=>/^[A-Z0-9_]+=/.test(x)).map(x=>{let i=x.indexOf('=');return[x.slice(0,i),x.slice(i+1).trim().replace(/^['"]|['"]$/g,'')]}));
(async()=>{const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:900}});let mode='main';const base='https://pr-1042.clarity-video.workers.dev';const auth=await stagingLogin(context.request,base+'/auth/password',{data:{email:env.E2E_USER_PRO_EMAIL,password:env.E2E_USER_PRO_PASSWORD}});if(!auth.ok())throw Error('Auth status '+auth.status());mode='branch';const page=await context.newPage();const results=[];let id;
try{const source=JSON.parse(fs.readFileSync('/tmp/verify-land/scripts/fixture.json')).data;const hero=source.blocks.find(b=>b.kind==='hero'),story=source.blocks.find(b=>b.kind==='story');hero.id=crypto.randomUUID();story.id=crypto.randomUUID();story.fields.title='';story.fields.body='';story.fields.media={assetId:'',assetType:'',imageId:'',videoId:''};const other=structuredClone(story);other.id=crypto.randomUUID();const r=await context.request.post(base+'/api/journey-pages',{data:{journey_page:{name:'Overnight verify LAND '+new Date().toISOString().slice(11,19),blocks:[hero,story,other]}}});if(r.status()!==201)throw Error('create '+r.status());id=(await r.json()).data.id;fs.writeFileSync(out+'/owned.json',JSON.stringify([id]));await page.goto(base+'/edit/'+id);await page.locator('[data-slot="save-status"][data-save-state="saved"]').waitFor({state:'attached'});
for(const [blockId,field,name,key,selector,text] of [[story.id,'title','Section title','Enter','h2[contenteditable]','Keyboard began empty title'],[other.id,'body','Description','Space','.ProseMirror','Keyboard began empty body']]){const section=page.locator('[data-section-id="'+blockId+'"]');const ghost=section.getByRole('button',{name,exact:true});await ghost.focus();await ghost.press(key);const editable=section.locator(selector);await editable.focus();await editable.press('ControlOrMeta+A');await editable.pressSequentially(text);await editable.press('Tab');await page.waitForTimeout(1500);await page.locator('[data-slot="save-status"][data-save-state="saved"]').waitFor({state:'attached'});await page.reload();await page.locator('[data-slot="save-status"][data-save-state="saved"]').waitFor({state:'attached'});const data=await(await context.request.get(base+'/api/journey-pages/'+id)).json();const stored=data.data.blocks.find(b=>b.id===blockId).fields[field];if(!stored.includes(text))throw Error('Stored value differs');fs.writeFileSync(out+'/'+field+'.json',JSON.stringify(data,null,2));await section.scrollIntoViewIfNeeded();await page.screenshot({path:out+'/'+field+'.png'});results.push({field,key,stored,status:'PASS'});}
}finally{if(id)results.push({cleanup:id,status:(await context.request.delete(base+'/api/journey-pages/'+id)).status(),getStatus:(await context.request.get(base+'/api/journey-pages/'+id)).status()});fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2));await browser.close();}console.log(JSON.stringify(results));})().catch(e=>{console.error(e.message);process.exitCode=1});
