process.env.TMPDIR='/tmp/verify-land';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root='/Users/williamlarsten/Development/clarity-overnight-1006/v-land',out='/Users/williamlarsten/Development/clarity-overnight-1006/verify/land/browser';
const pw=require(root+'/node_modules/playwright');const originalLaunch=pw.chromium.launch.bind(pw.chromium);
const run=process.env.PROOF_OUT||process.argv[1];const token=crypto.randomUUID().slice(0,8);let screenshots=0;
function append(name,x){fs.appendFileSync(out+'/'+name,JSON.stringify({time:new Date().toISOString(),run,...x})+'\n')}
pw.chromium.launch=async opts=>{const browser=await originalLaunch({...opts,args:[...(opts?.args||[]),'--disable-dev-shm-usage']});const exitWatch=setInterval(()=>{if(process.exitCode)browser.close().catch(()=>{})},1000);exitWatch.unref();browser.on('disconnected',()=>clearInterval(exitWatch));const newContext=browser.newContext.bind(browser);browser.newContext=async opts=>{const ctx=await newContext(opts);await ctx.route('**/*',r=>{const q=r.request(),u=new URL(q.url());return q.isNavigationRequest()&&q.frame()===q.frame().page().mainFrame()&&u.protocol==='https:'&&u.hostname!=='pr-1042.clarity-video.workers.dev'?r.abort():r.continue()});const owned=new Set();const fulfilled=new Set();const routeOriginal=ctx.route.bind(ctx);ctx.route=async(pattern,handler,...rest)=>routeOriginal(pattern,async route=>{const original=route.fulfill.bind(route);route.fulfill=async opts=>{if(opts.path&&/\/assets\//.test(opts.path)&&!fulfilled.has(opts.path)){fulfilled.add(opts.path);append('asset-delivery.ndjson',{path:opts.path,sha256:crypto.createHash('sha256').update(fs.readFileSync(opts.path)).digest('hex')});}return original(opts)};return handler(route)},...rest);const api=ctx.request;
for(const method of ['post','put','patch','delete']){const orig=api[method].bind(api);api[method]=async(url,opts)=>{const u=new URL(url);if(u.pathname.startsWith('/api/journey-pages')){const id=u.pathname.split('/')[3];if(method!=='post'&&!owned.has(id))throw Error('Refuse unowned write '+id);if(method==='post'){opts=structuredClone(opts);opts.data.journey_page.name+=' '+token;append('ownership-ledger.ndjson',{event:'create-intent',name:opts.data.journey_page.name});}const r=await orig(url,opts);if(method==='post'&&r.ok()){const j=await r.json();owned.add(j.data.id);append('ownership-ledger.ndjson',{event:'created',id:j.data.id,name:j.data.name});}append('api-writes.ndjson',{method,path:u.pathname,status:r.status()});return r;}return orig(url,opts)}}
const newPage=ctx.newPage.bind(ctx);ctx.newPage=async()=>{const p=await newPage();p.setDefaultNavigationTimeout(30000);const go=p.goto.bind(p);p.goto=async(...args)=>{args[1]={...args[1],waitUntil:'domcontentloaded'};let r=await go(...args);if(String(args[0]).includes('/edit/')){try{await p.locator('[data-slot=save-status]').waitFor({timeout:10000,state:'attached'})}catch(e){append('setup-retries.ndjson',{url:args[0],reason:'Editor not ready after navigation; retry read-only navigation'});r=await go(...args);await p.locator('[data-slot=save-status]').waitFor({timeout:30000,state:'attached'});}}return r};const reload=p.reload.bind(p);p.reload=opts=>reload({...opts,waitUntil:'domcontentloaded'});const shot=p.screenshot.bind(p);p.screenshot=async opts=>{const name=path.basename(opts?.path||'');if(!/representative|failure|panel\.png|layout-|before\.png|after\.png|reopen|keyboard-link-access|save-error|hero-tab|adjacent|public|placement|seam/.test(name)||screenshots>=30)return Buffer.alloc(0);screenshots++;return shot({...opts,fullPage:false})};p.on('request',r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/journey-pages')&&['PUT','PATCH','DELETE'].includes(r.method())){const id=u.pathname.split('/')[3];if(!owned.has(id)){append('safety-failures.ndjson',{path:u.pathname,method:r.method()});p.close();}}});p.on('response',async r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/journey-pages')&&r.request().method()==='PUT'){append('browser-saves.ndjson',{id:u.pathname.split('/')[3],status:r.status()})}});return p};return ctx};return browser};module.exports=pw;
