from pathlib import Path
import json,html,datetime,collections,shutil
r=Path('/Users/williamlarsten/Development/clarity-overnight-1006/verify/land/browser');base='https://pr-1042.clarity-video.workers.dev';sha='6c8c169b4f1fc05bebcb434e42432eac40f0cd89';now=datetime.datetime.now(datetime.timezone.utc).isoformat();rows=json.loads((r/'coverage.json').read_text());cleanup=json.loads((r/'cleanup.json').read_text());audit=json.loads((r/'api-value-audit.json').read_text())
screens=[('story-hit/representative-Left.png','Failure. The resize grip overlaps the Left alignment control for a 640 by 100 story image.'),('visual/representative-Plan 1 title.png','The caret is visible within the pricing name.'),('visual/representative-Plan 1 price.png','The caret is visible between digits in the pricing price.'),('visual/representative-Aurora-caret.png','The caret is visible in the Aurora heading.'),('wide-logo-final/representative-wide-logo-loaded.png','The loaded wide logo is contained within the Style thumbnail. The default-logo action is visible.'),('extras-complete/representative-logo-picker.png','After selecting a logo, the picker offers Use on new pages too.'),('video-final/representative-pointer-hero-video-modal.png','Pointer activation of Edit video opens the hero video editor.'),('video-final/representative-keyboard-story-video-modal.png','Keyboard activation of Edit video opens the story video editor.'),('extras-complete/representative-media-radius.png','The media outline and image both use the theme corner radius, measured as 20 pixels.'),('extras-complete/representative-published.png','The published preview renders the saved heading and image. DOM assertions also confirmed the pricing plan farther down the page.'),('adjacent-land/adjacent-home.png','The library loaded without console errors.'),('adjacent-land/adjacent-record.png','The recorder loaded without console errors. This headless browser has no camera or microphone.'),('adjacent-land/adjacent-settings-branding.png','Branding settings loaded without console errors. The temporary test logo shown here was removed during cleanup.')]
# Every screenshot included below was opened with view_image.
(r/'screenshot-inspection.json').write_text(json.dumps({'inspectedAt':now,'method':'view_image','screenshots':[dict(path=p,caption=c)for p,c in screens]},indent=2))
checks=[('Exact preview identity','PASS','Login then doctor --pr 1042 --wait. Final doctor matches the requested head.','doctor-final.txt'),('All 191 coverage rows','FAIL','190 pass, 1 fails, 0 not testable. Row 56 fails by pointer.','coverage.json'),('UI saves and API values','FAIL','466 successful browser PUT responses. 233 of 234 stored-value assertions pass; the single failure is the blocked Left alignment. Other suites also use inline API predicates.','api-value-audit.json'),('No old editor side panel','PASS','Old editor-panel and editor-form are absent. Hero has no removal handle.','extras-complete/panel-hero.json'),('Hero and story video controls','PASS','Edit video, Replace, add and remove pass by pointer and keyboard. Replace remains open after its opening press.','video-final/results.json'),('Logo defaults and wide thumbnail','PASS','Picker checkbox and Style default action are present. Loaded image is 640 by 100 and uses object-fit contain.','wide-logo-final/wide-logo-measured.json'),('Visible carets','PASS','Pricing name, price and Aurora heading inspected in screenshots with caret initial.','visual/results.json'),('Pricing Enter and Backspace','PASS','Enter creates the second feature. Backspace on the empty second feature removes it. Both survive reload.','extras-complete/results.json'),('Theme radius on media outline','PASS','Overlay and image both have border-radius 20px, matching --jp-radius.','extras-complete/media-radius.json'),('Theme and Style saves','PASS','Preset, accent, background, font, size, corners and logo alignment saved and reloaded.','extras-complete/results.json'),('Publish and public rendering','PASS','UI Publish returned 200 and opened a public link. Its heading and pricing plan matched the saved edits.','extras-complete/public.json'),('Library, recorder and settings','PASS','Each route loaded with no console or page errors.','adjacent-land/results.json'),('Existing keyboard rich-text link gap','WARN','Tab skips the link toolbar for story, form and pricing. Pointer add, edit and remove links pass. This gap is already recorded in the supplied checklist.','rich/results.json'),('Save failure recovery','PASS','One deliberate 503 produced an explanatory alert. Removing the interception allowed a real save and reload.','special-land/save-error-recovered.json'),('Fixture cleanup','PASS','44 pages and 2 public URLs return 404. Four owned media assets were deleted and return 404. The default logo is null with legacy preference again.','cleanup.json'),('Build, tests and diff audit','NOT RUN','Assigned to the parent. No product code changed.','')]
finding='''Blocker for browser acceptance: the story resize handle intercepts Left alignment on a short, wide image.

Code location: `editor/src/components/editor/JourneyMediaResizer.tsx:151`, where the resize hit area has an 80-pixel height, a 44-pixel width and z-index 6. The toolbar is rendered in `editor/src/components/MediaPicker.tsx:326`.

1. On the exact preview head, create a page with a story block. Use a 1440 by 1000 viewport.
2. Add a 640 by 100 image to the story. This run used its own `LAND-logo-1.png`.
3. Hover the media and click Right. Wait for save, reload, and hover it again.
4. Click the center of Left in the media toolbar. The resize handle receives the click. The saved `mediaSide` remains `right` after reload.

The measured Left button spans x=931.5 to 963.5 and y=532.171875 to 564.171875. At its center, `elementFromPoint` returns the Resize media button. Six of the nine sampled interior points hit Resize media. A direct mouse click, with no forced locator action, reproduces the unchanged API value. Keyboard activation does save `left`.

Expected fix: prevent the resize hit area from covering toolbar buttons, for example by giving the toolbar precedence or excluding its bounds from the resize target. Recheck short landscape media on both alignments.

Evidence: [hit test](story-hit/Left-hit.json), [saved wrong value](story-hit/story-media-Left.json), [screenshot](story-hit/representative-Left.png), [reproduction commands](story-hit/commands.txt), [keyboard control](canonical-keyboard/story-media-Left.json). This run did not compare the same shape against main, so it does not claim when the obstruction was introduced.'''
intro=f'''NOT VERIFIED | {base} | {sha}

Independent browser acceptance at the exact PR #1042 head. Completed {now}. All 191 supplied coverage rows ran fresh: 190 pass, 1 fails, 0 are not testable. The failure is row 56, story media alignment Left by pointer on a short, wide image. Other LAND acceptance checks pass.

This report covers live preview browser work only. The parent owns build gates and the diff audit. No product edits, commits, pushes, GitHub comments or deploys were made. No artifacts were published externally.
'''
md=intro+'\n## LAND checks\n\n| Check | Result | Evidence |\n| --- | --- | --- |\n'
for n,s,note,p in checks:md+=f'| {n} | {s} | {note} '+(f'[{p}]({p})'if p else '')+' |\n'
md+='\n## Finding\n\n'+finding+'\n\n## Coverage\n\n| Row | Capability | Result | Evidence | Notes |\n| --- | --- | --- | --- | --- |\n'
for x in rows:md+=f"| {x['row']} | {x['capability']} | {x['status']} | "+', '.join(f'[{p}]({p})'for p in x['evidence'])+f" | {x['notes']} |\n"
md+='''
## Evidence limits and cleanup

The scripts create owned fixtures through the preview API and perform the acceptance mutations through the UI. Saved-state waits, reloads, rendered snapshots and real API reads back each edit. Existing seeded video assets were selected but never edited or deleted. Earlier attempts with stale staging fixture names, immediate DOM counts, missing hover states or unnamed-dialog assumptions remain in their attempt directories; the coverage table points to the fresh successful rechecks.

The screenshot audit caught Playwright's default caret hiding and a logo thumbnail captured before decode. The final visual evidence uses `caret: initial` and waits for the thumbnail to decode. The wide thumbnail's container does not need to match the image aspect ratio because `object-fit: contain` preserves the whole image.

The fresh pointer link operations pass for story, form and pricing. Their existing keyboard toolbar gap remains a follow-up, as recorded in the supplied coverage table. The accepted concurrent-writer cases were not tested. Recorder route loading passed, but no recording was attempted with this headless browser's absent devices.

Final relevant suites have no console or page errors. The two aborted requests in canonical-keyboard and pointer-retry occurred during navigation. One 503 was deliberately simulated for the save-error check and then removed. Initial restrictive media-request attempts are superseded by the final media and visual runs. Browser navigation stayed on the PR preview; the app fetched its normal media and font dependencies.

All 44 created page IDs independently return 404. Both published URLs return 404. All four uploaded test media nodes were deleted and their path reads return 404. The logo picker initially defaulted to saving the test logo for new pages. Deleting that owned logo restored a null default with legacy preference. Later logo checks explicitly unchecked that choice. The cleanup details are in [cleanup.json](cleanup.json). Every raw Playwright browser process started by this run closed.

The self-contained HTML report is [report.html](report.html). Screenshots were opened with the image-viewing tool; the captions and paths are in [screenshot-inspection.json](screenshot-inspection.json).
'''
(r/'REPORT.md').write_text(md)
# Self-contained report styling; all evidence and screenshots remain local.
e=html.escape
parts=[f'<!doctype html><html lang="en"><meta charset="utf-8"><title>PR 1042 browser verification</title><style>body{{font:16px/1.5 system-ui;max-width:1200px;margin:40px auto;padding:0 24px;color:#182133}}header{{border-left:8px solid #b42318;background:#fff1f0;padding:20px}}table{{border-collapse:collapse;width:100%;font-size:14px}}th,td{{border:1px solid #d7dce3;padding:8px;text-align:left;vertical-align:top}}th{{background:#f3f5f8}}a{{color:#1358b8;overflow-wrap:anywhere}}code{{overflow-wrap:anywhere}}figure{{margin:28px 0}}img{{max-width:100%;border:1px solid #ccd2dc}}.fail{{color:#b42318}}.pass{{color:#146b3a}}.warn{{color:#8b5600}}pre{{white-space:pre-wrap;background:#f7f8fa;padding:20px}}h2{{margin-top:40px}}</style><header><h1>NOT VERIFIED</h1><p>PR preview · Independent browser run and artifact audit</p><p>{e(base)}<br><code>{sha}</code><br>{now}</p><p>190 of 191 rows pass. One pointer obstruction blocks browser acceptance. The parent owns gates and diff review.</p></header><h2>LAND checks</h2><table><tr><th>Check</th><th>Result</th><th>Evidence</th></tr>']
for n,s,note,p in checks:parts.append(f'<tr><td>{e(n)}</td><td class="{s.lower()}">{s}</td><td>{e(note)} '+(f'<a href="{e(p)}">Evidence</a>'if p else '')+'</td></tr>')
parts.append('</table><h2>Finding and reproduction</h2><pre>'+e(finding)+'</pre><p>This is a current-head failure. No before/main browser comparison was requested for this bounded run.</p><h2>Coverage</h2><table><tr><th>Row</th><th>Capability</th><th>Result</th><th>Evidence</th><th>Notes</th></tr>')
for x in rows:parts.append(f'<tr><td>{x["row"]}</td><td>{e(x["capability"])}</td><td class="{x["status"].lower()}">{x["status"]}</td><td>'+', '.join(f'<a href="{e(p)}">{e(p)}</a>'for p in x['evidence'])+f'</td><td>{e(x["notes"])}</td></tr>')
parts.append('</table><h2>Inspected screenshots</h2>')
for p,c in screens:
 suite=p.split('/')[0];created=r/suite/'created.json';url=base
 if created.exists():url+='/edit/'+json.loads(created.read_text())['data']['id']
 if 'published' in p:url=json.loads((r/'extras-complete/public.json').read_text())['url']
 if p.startswith('adjacent-land/'):url=base+('/record'if'record'in p else '/settings/branding'if'settings'in p else'/home')
 parts.append(f'<figure><img src="{e(p)}" alt="{e(c)}"><figcaption>{e(c)}<br><small>{e(url)}. Test pages have been deleted.</small></figcaption></figure>')
parts.append('<h2>Console, network and cleanup</h2><p>466 successful browser PUT responses. One deliberate 503 verified save-error explanation and recovery. The final video, visual and adjacent-route runs had no console or page errors. The recorder displayed its no-device state. Two navigation-aborted requests were retained in canonical-keyboard and pointer-retry.</p><p>44 owned pages, both published URLs and four uploaded media assets now return 404. The workspace default logo is null with legacy preference again. No external artifacts were published.</p><p><a href="cleanup.json">Cleanup evidence</a> · <a href="browser-saves.ndjson">Browser writes</a> · <a href="api-value-audit.json">Stored-value audit</a> · <a href="REPORT.md">Full Markdown report and limitations</a></p></html>')
(r/'report.html').write_text(''.join(parts))
with (r/'progress.log').open('a')as f:f.write(now+' Report written. 191 rows: 190 pass, 1 fail. Cleanup verified for 44 pages, 4 assets and 2 public URLs.\n')
print('Report written',len(rows),'rows',len(screens),'screenshots')
