const base='https://pr-1042.clarity-video.workers.dev';
const field=(j,k)=>{const f=j.data.blocks.find(b=>b.kind===k).fields;return k==='story'?f.body:k==='form'?f.form.form_description:f.pricings[0].description};
async function resetRich(k,linked=false){const j=await(await context.request.get(base+'/api/journey-pages/'+id)).json();const f=j.data.blocks.find(b=>b.kind===k).fields,html=linked?'<p><a href="https://example.com/old">Formatted sentence</a></p>':'<p>Formatted sentence</p>';if(k==='story')f.body=html;else if(k==='form')f.form.form_description=html;else f.pricings[0].description=html;await context.request.put(base+'/api/journey-pages/'+id,{data:{journey_page:j.data,base_revision:j.revision}});await page.reload();await page.locator('[data-save-state=saved]').waitFor({state:'attached'});return page.locator(mode==='main'?'.accordion-section[data-section-kind='+k+']':'[data-slot=journey-preview] [data-section-kind='+k+']').locator('.ProseMirror').first()}
for(mode of ['branch'])for(const kind of ['story','form','pricing'])for(const input of ['pointer','keyboard']){
 for(const [name,tag,shortcut] of [['Bold','strong','ControlOrMeta+b'],['Italic','em','ControlOrMeta+i'],['Bullet list','ul','ControlOrMeta+Shift+8'],['Numbered list','ol','ControlOrMeta+Shift+7']]){
  await test(mode+'-'+kind+'-'+input+'-'+name.replaceAll(' ','-'),async()=>{const l=await resetRich(kind);if(input==='pointer')await l.click();else await l.focus();await l.press('ControlOrMeta+A');await page.waitForTimeout(150);if(input==='pointer')await (mode==='main'?page.locator('.accordion-section[data-section-kind='+kind+']'):page.locator('[data-slot=canvas-text-toolbar]:visible').last()).getByRole('button',{name,exact:true}).first().click();else await l.press(shortcut);await page.keyboard.press('Tab');await saved(mode+'-'+kind+'-'+input+'-'+name.replaceAll(' ','-'),j=>field(j,kind).includes('<'+tag));});await page.keyboard.press('Escape');
 }
 if(input==='pointer')for(const action of ['Add link','Edit link','Remove link'])await test(mode+'-'+kind+'-'+action.replaceAll(' ','-'),async()=>{const l=await resetRich(kind,action!=='Add link');await l.click();await l.press('ControlOrMeta+A');await page.waitForTimeout(150);await (mode==='main'?page.locator('.accordion-section[data-section-kind='+kind+']'):page.locator('[data-slot=canvas-text-toolbar]:visible').last()).getByRole('button',{name:action,exact:true}).first().click();if(action!=='Remove link'){await page.getByRole('textbox',{name:'Link destination'}).fill('https://example.com/verified');await page.keyboard.press('Enter')}await page.keyboard.press('Tab');await saved(mode+'-'+kind+'-'+action.replaceAll(' ','-'),j=>action==='Remove link'?!field(j,kind).includes('href='):field(j,kind).includes('https://example.com/verified'))});
 else await test(mode+'-'+kind+'-keyboard-link-access',async()=>{const l=await resetRich(kind);await l.focus();await l.press('ControlOrMeta+A');await page.waitForTimeout(200);const stops=[];for(const key of ['Tab','Shift+Tab','Shift+Tab']){await page.keyboard.press(key);stops.push(await page.evaluate(()=>({tag:document.activeElement.tagName,label:document.activeElement.getAttribute('aria-label'),text:document.activeElement.textContent?.slice(0,50)})))}await l.focus();await l.press('ControlOrMeta+A');await l.press('ControlOrMeta+k');await page.waitForTimeout(200);const visible=await page.getByRole('textbox',{name:'Link destination'}).isVisible();fs.writeFileSync(out+'/'+mode+'-'+kind+'-keyboard-link-access.json',JSON.stringify({stops,linkShortcutOpened:visible,toolbar:await page.getByRole('button',{name:'Add link',exact:true}).evaluateAll(es=>es.map(e=>({tabIndex:e.tabIndex,visible:!!e.getBoundingClientRect().width})))},null,2));await shot(mode+'-'+kind+'-keyboard-link-access');if(!visible)throw Error('Keyboard link shortcut unavailable; Tab skips toolbar');});
}
