async function stagingLogin(req,url,opts){for(let attempt=0;attempt<6;attempt++){try{return await req.post(url,opts)}catch(e){if(attempt===5||!/EHOSTUNREACH|ECONNREFUSED|ETIMEDOUT/.test(e.message))throw e;await new Promise(r=>setTimeout(r,700));}}}
process.env.NODE_OPTIONS=[process.env.NODE_OPTIONS,'--dns-result-order=ipv4first'].filter(Boolean).join(' ');
require('node:dns').setDefaultResultOrder('ipv4first');
const fs=require('fs'),path=require('path'),readline=require('readline');
const root='/Users/williamlarsten/Development/clarity-overnight-1006/v-land';
const out=process.env.PROOF_OUT;fs.mkdirSync(out,{recursive:true});
if(fs.existsSync(out+'/completed.marker'))process.exit(0);try{fs.mkdirSync(out+'/.running')}catch{process.exit(0)}
const {chromium}=require('./instrument.cjs');
const env=Object.fromEntries(fs.readFileSync(root+'/.env.e2e.local','utf8').split('\n').filter(x=>/^[A-Z0-9_]+=/.test(x)).map(x=>{let i=x.indexOf('=');return [x.slice(0,i),x.slice(i+1).trim().replace(/^['"]|['"]$/g,'')]}));
let browser,context,page,id; let mode=process.env.PROOF_MODE||'branch',seq=0; const owned=[],results=[],errors=[],network=[],assets=[];
const log=x=>{fs.appendFileSync(require('path').dirname(out)+'/progress.log',new Date().toISOString()+' '+require('path').basename(out)+' '+JSON.stringify(x)+'\n');fs.writeFileSync(out+'/progress.txt',new Date().toISOString()+' '+JSON.stringify(x));console.log(JSON.stringify(x));fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2));};
async function cleanup(){for(const pid of owned){const r=await context.request.delete('https://pr-1042.clarity-video.workers.dev/api/journey-pages/'+pid);results.push({cleanup:pid,status:r.status(),getStatus:(await context.request.get('https://pr-1042.clarity-video.workers.dev/api/journey-pages/'+pid)).status()});}fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2));fs.writeFileSync(out+'/network.json',JSON.stringify(network,null,2));fs.writeFileSync(out+'/assets.json',JSON.stringify(assets,null,2));await browser?.close();fs.writeFileSync(out+'/completed.marker',new Date().toISOString());fs.rmdirSync(out+'/.running');}
async function shot(name){await page.screenshot({path:out+'/'+name+'.png',fullPage:false,timeout:60000});}
async function snap(){return await page.locator('body').ariaSnapshot();}
async function saved(name,check){await page.waitForTimeout(1500);await page.locator('[data-slot="save-status"][data-save-state="saved"]').waitFor({timeout:45000,state:'attached'});id=new URL(page.url()).pathname.split('/').pop();if(!owned.includes(id))throw Error('Refuse unowned draft '+id);fs.writeFileSync(out+'/owned.json',JSON.stringify(owned));await page.reload();await page.locator('[data-slot="save-status"][data-save-state="saved"]').waitFor({timeout:60000,state:'attached'});const r=await context.request.get('https://pr-1042.clarity-video.workers.dev/api/journey-pages/'+id);const data=await r.json();fs.writeFileSync(out+'/'+name+'.json',JSON.stringify(data,null,2));if(check&&!check(data))throw Error('API assertion failed '+name);fs.writeFileSync(out+'/'+name+'-rendered.json',JSON.stringify(await page.locator('[data-slot=journey-preview],[data-slot=editor-panel]').evaluateAll(es=>es.map(e=>({slot:e.getAttribute('data-slot'),text:e.innerText,inputs:[...e.querySelectorAll('input,textarea')].map(i=>({label:i.getAttribute('aria-label'),value:i.value}))})))));await page.waitForTimeout(400);const parts=name.split('-');const raw=parts.find(x=>['hero','story','logos','gallery','form','document','faq','pricing','summary','plan','feature','logo'].includes(x))||parts[0];const kind=raw==='plan'||raw==='feature'?'pricing':raw==='logo'?'logos':raw;const loc=page.locator(mode==='main'?'.accordion-section[data-section-kind='+kind+']':'[data-slot=journey-preview] [data-section-kind='+kind+']');if(await loc.count())await loc.first().scrollIntoViewIfNeeded();if(name==='plan-add')fs.writeFileSync(out+'/'+name+'-dom.txt',await snap());fs.writeFileSync(out+'/'+name+'-surface.json',JSON.stringify({mode,panel:await page.locator('[data-slot=editor-panel]').count(),form:await page.locator('[data-slot=editor-form]').count()}));await shot(name);results.push({name,mode,status:'PASS',snapshot:name+'.json',...(fs.existsSync(out+'/'+name+'.png')?{screenshot:name+'.png'}:{})});fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2));return data;}
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message});await shot(name+'-failure').catch(()=>{});}log(results.at(-1));}
(async()=>{browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();page.setDefaultTimeout(20000);page.on('response',async r=>{const u=new URL(r.url());if(r.status()>=400)errors.push({mode,type:'http',status:r.status(),path:u.pathname});if(u.pathname.startsWith('/api/'))network.push({method:r.request().method(),path:u.pathname,status:r.status()});if(u.pathname.startsWith('/assets/')&&u.pathname.endsWith('.js')){const d=mode==='main'?'/tmp/verify-e-main-dist':'/tmp/verify-land/head-dist';if(fs.existsSync(d+u.pathname)){try{const bytes=await r.body(),local=fs.readFileSync(d+u.pathname),hash=b=>require('crypto').createHash('sha256').update(b).digest('hex');if(!assets.some(a=>a.mode===mode&&a.path===u.pathname))assets.push({mode,path:u.pathname,fetched:hash(bytes),local:hash(local),equal:bytes.equals(local)});}catch{}}}});
page.on('console',m=>{if(m.type()==='error')errors.push({mode,type:'console',text:m.text()});fs.writeFileSync(out+'/errors.json',JSON.stringify(errors,null,2))});page.on('pageerror',e=>{errors.push({mode,type:'pageerror',text:e.message});fs.writeFileSync(out+'/errors.json',JSON.stringify(errors,null,2))});page.on('requestfailed',r=>{errors.push({mode,type:'requestfailed',url:r.url(),error:r.failure()});fs.writeFileSync(out+'/errors.json',JSON.stringify(errors,null,2))});

const auth=await stagingLogin(context.request,'https://pr-1042.clarity-video.workers.dev/auth/password',{data:{email:env.E2E_USER_PRO_EMAIL,password:env.E2E_USER_PRO_PASSWORD}});if(!auth.ok())throw Error('Login status '+auth.status());const me=await context.request.get('https://pr-1042.clarity-video.workers.dev/auth/me');if(!(await me.json()).data)throw Error('Empty identity');fs.writeFileSync(out+'/doctor.json',JSON.stringify({auth:me.status(),deploy:await(await context.request.get('https://pr-1042.clarity-video.workers.dev/__deploy-info')).json()}));log({ready:true});
const commands=fs.readFileSync(process.env.PROOF_COMMANDS,'utf8').split('\n').filter(Boolean);for(const line of commands){if(line==='QUIT')break;fs.appendFileSync(out+'/commands.txt',line+'\n');try{const val=await eval('(async()=>{'+line+'})()');log({value:val});}catch(e){results.push({status:'ERROR',error:e.stack});log({error:e.stack});await shot('setup-failure').catch(()=>{});fs.writeFileSync(out+'/setup-state.json',JSON.stringify({url:page.url(),states:await page.locator('[data-slot=save-status]').evaluateAll(es=>es.map(e=>e.getAttribute('data-save-state'))).catch(()=>[])}));if(!results.some(x=>x.name==='created'&&x.status==='PASS'))break;}if(line==='QUIT')break;}await cleanup();})().catch(async e=>{console.log(e.message);await cleanup().catch(()=>{});process.exit(1)});
